### ISSUE TITLE
Field App - Workforce Labor - Copy

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#10]
Users would like to be able to copy/duplicate labor records within the workforce labor entry screen, instead of having to manually enter line by line each operator.  

Example – there are 25 dump trucks with 25 operators.  In the equipment screen the user is able to enter the amount of equipment used (25), but in the workforce labor screen a separate line item entry is required for each operator.  Would like to see this simplified by giving the user the ability to duplicate the record ‘X’ number of times.

**Comment by ehsan67** [comment]
developed , waiting for feedback

**Comment by arheimberger** [comment]
Current testing for this enhancement has been good.  We still experience the intermittent save issue within labor, but the duplication works well.  I have duplicated, edited, deleted, etc without issue.  I generated a few reports (HOCO and General) to test out how the laborers would display and they are all working well.

**Comment by arheimberger** [comment]
Duplicate labor is working well.  

Labor screen update in testing version 1.1.1.55 (June 2015) has been successful thus far in eliminating the save validation issues.
