### ISSUE TITLE
New Report - CM / South Carolina DOT

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#29]
New report requested for South Carolina CM group, client is DOT.

Image attached, we have some flexibility in format.  We can review when you are ready to begin working on this one.
![sc dot idr example](https://cloud.githubusercontent.com/assets/6420664/4735341/ab1818fa-59df-11e4-8c71-70bdf1e40b99.PNG)

**Comment by ehsan67** [comment]
developed
