### ISSUE TITLE
Job Hazard Analysis - Enhancement

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#32]
Would it be possible to have a specific Job Hazard Analysis checklist based either on project or user group for the project?  If we based it on project level, could we do something in IR Config to select which checklist version needs to be completed.

Just a thought at this point, but wanted to capture the idea as it might come up as a result of demo's to the Gas/Energy industry.

**Comment by ehsan67** [comment]
It is only required for KCI inspectors

**Comment by ehsan67** [comment]
it is done, based on User's email address

**Comment by arheimberger** [comment]
Working well in latest release (April 2015)
