### ISSUE TITLE
Attachment - Duplicating Images

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#34]
Attachment images are duplicating when saving several attachments at a time, and the same name is given to more then one attachment.  
This process does not occur as you are adding the artifact, but once you complete the save on the section you are in.  We need the system to add a differentiating character to the name so that this does not cause an issue.  This has to be validated at the time the attachment file is saved.

Steps to recreate:
-Open the 'Comments' section of an inspection, select General Remark, and enter a generic comment
-Select the 'Attachments' artifact section
-Add an image from the camera roll
-Name the image 'Test123', location is 'Photos', type is 'Sketch-General'
-Save the attachement
-Click (+) on 'Attachements' to add another attachment, select a different image
-Name the image 'Test123', location is 'Photos', type is 'Sketch-General'
-Note images are different
-Click SAVE to save the comment
-Tap the white box of the comment and then edit the form
-Observe images are now the same image, not the original 2 different images

**Work around is to save one attachment at a time.

![attachment duplicating](https://cloud.githubusercontent.com/assets/6420664/4902305/7e69a400-6438-11e4-89ce-bc555951a4df.png)

**Comment by ehsan67** [comment]
fixed
