### ISSUE TITLE
Upload IDR - function not working

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#43]
The Upload IDR button does not appear to be functioning as designed.  

When we create an IDR, receive the report via email, place a signature on it through PDF and save, return to the MFS program and click the 'Upload IDR' button, nothing appears to happen.

Tested a few times on an inspector's tablet, and I have tested on mine as well.

**Comment by ehsan67** [comment]
fixed, please test it again in the next build

**Comment by arheimberger** [comment]
tested successfully in 1.1.1.51
