### ISSUE TITLE
SUE - Pole Inspection Form - New Report

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#44]
SUE has identified a new area they would like to create a report for and deploy the MFS application to - Pole Inspection.

This new report comes with a new set of custom questions (work item type: Declared Circuit).  The layout is flexible, and attached you will find a general layout to follow.  I will send the excel file so that you can see the possible answers to the questions, many are drop down selections.  The layout should be formatted so that fields line up where possible and lines begin and end at the same spot on the right and left hand side of the page.  

We can review in person when you are ready to begin this new report.

This report will be replicated for other work item types to be built after this report is finalized.

![pole insp capture](https://cloud.githubusercontent.com/assets/6420664/5630207/915a8246-9589-11e4-9546-e02738319f82.PNG)

**Comment by ehsan67** [comment]
developed
