### ISSUE TITLE
CI - Splice Report

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#46]
New report request from the Splice Team looking to implement MFS for their field technicians.

Report will be based on custom questions for work item types:
Splice - 2 Cable, Splice - 3 Cable, Splice - 4 Cable, Splice - 5 Cable, Splice - 6 Cable, Splice - Building

Artifacts associated to the work item details should be displayed following the work item details, not grouped at the end of the report.

A draft layout is attached.
![splice report capture](https://cloud.githubusercontent.com/assets/6420664/5941311/269d621e-a6de-11e4-80af-ae9fbc8aa5cc.JPG)

**Comment by ehsan67** [comment]
developed, waiting for feedback and possible changes
