### ISSUE TITLE
Labor - Save Issue (Intermittent)

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#49]
Within the labor tab of a work item, sometimes the save button will not enable after all required fields are completed.  

This is an intermittent issue, sometimes it will occur after one entry, sometimes after 5.  Exiting and re-entering the screen does not resolve the issue once it has occurred on a work item.

Steps to recreate:
Select a work item
Click the (+) on the labor section to add a new entry
Enter all required fields, including laborer details (name and hours)
Randomly you will observe the save button is not enabled.

**Comment by arheimberger** [comment]
Turn off Labor Validation prior to next release.  Add a pop up error when all required fields are not completed.

**Comment by ehsan67** [comment]
fixed, needs to be tested

**Comment by arheimberger** [comment]
Corrected in version 1.2.1.11
