### ISSUE TITLE
New Geolocation Pin Functionality

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#54]
It appears that once a geolocation is added and saved, the user cannot make a change to the pin to get a new X, Y for the updated location.  The user can move the pin, and save the image, or clear the map and add a new geolocation pin, but the original X, Y still remains for the first location saved.

**Comment by arheimberger** [comment]
Tested - the X, Y captured at the initial 'Add Geolocation' is the X, Y that stays, even if the pin is moved prior to saving the map image.  The X, Y is from the original placement of the Geolocation Pin.

**Comment by ehsan67** [comment]
fixed
