### ISSUE TITLE
New Report - MdTA IDR

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#56]
The report layout is very similar to the SHA report.  Attached are images of the blank copies, I have a physical copy with notes for us to review when you are ready to begin working on this one.  This needs to be completed by 4/1 for testing as it is part of the MdTA pilot deployment of external users on MFS which has a roll out ETA of the end of April.

![mdta idr image 1](https://cloud.githubusercontent.com/assets/6420664/6664816/5fbc2860-cba9-11e4-9ef9-5d6a6133dd48.JPG)
![mdta idr image 2](https://cloud.githubusercontent.com/assets/6420664/6664817/628d8142-cba9-11e4-99f5-ab57780c7ca2.JPG)

**Comment by ehsan67** [comment]
almost complete , needs some testing

**Comment by arheimberger** [comment]
Completed and in use on version 1.1.2.11 by MDTA on Key Bridge project.
