### ISSUE TITLE
Initial Sync - Large Amount of Files

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#59]
On the latest release we had an issue with a user's initial sync taking a significant amount of time.  After investigating, it was determined that the long sync time was due to the amount of files that were in the user's history for their project (Project had 164 historical inspections with an average of 10 photos per inspection).

For the next release we need to discuss how to handle loading historical inspections so that this does not happen again, as we will see more of this as the user base grows and continues its use of the application.

**Comment by ehsan67** [comment]
Implemented
