### ISSUE TITLE
Field App - Daily Vehicle Checklist

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#6]
Daily Vehicle Checklist – allow alpha in the vehicle # field to enable users to enter ‘personal’ when a KCI Vehicle number is NA.  Currently these fields only accept numerical inputs, we have many inspectors that do not have a KCI vehicle.  

*Taking this one step further, if personal is entered, could we bypass the checklist, is that necessary on a personal vehicle?

**Comment by ehsan67** [comment]
Bypass is done

**Comment by arheimberger** [comment]
Personal Vehicle button for bypass successful and accepted among users.
