### ISSUE TITLE
Inspection Date - Incorrect 

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#60]
When a user creates an inspection after 8pm, the inspection creation date converts to the next day's date (presumably because of UTC conversion pushing it into the next day based on the time).  

This is causing issues for our users that are entering their inspections in the evening.  The user does not see the change until the sync has happened, regardless of that, there is no way for them to change the date to correct it on the inspection.

Here is an example of a recent inspection with this issue, created on the 7th, with a date of the 8th.
j.j-03H57M31S-80

**Comment by ehsan67** [comment]
Unable to recreate
