### ISSUE TITLE
Work Item - Add New Work Item 

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#62]
Within the Work Items tab of the Field Application, users have the the ability to 'Add a New Work Item' if the item they need is not on the existing list.  All fields are available with the exception of unit price and status.

When testing the functionality out with 2 users assigned to the same project.  It appears that a new work item added by User A cannot be seen by User B for that project.  We completed the sync of User A prior to User B syncing to see if he would receive the new work item.  

This needs further testing by Ashley and Ehsan, if confirmed a change will need to be made to allow all users on a project to see all work items added by other users.  

**We also need to consider/discuss how to flag work items added by field users when they are returned to the portal so that a project manager is aware of the new items can add pricing information if needed.

**Comment by ehsan67** [comment]
Fixed

**Comment by ehsan67** [comment]
to be tested in production

**Comment by arheimberger** [comment]
Resolved in 1.2.1.11
