### ISSUE TITLE
General Report

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#63]
A request was made for an enhancement to the General Report.

Is it possible to change the design/layout so that only sections with data entered are displayed on the report?  Currently all sections available are displayed, and that can make the report appear to be missing information to the client.  If we only display the sections with information the report will be a cleaner format to deliver.

Please advise is this is possible and I can document further.

**Comment by ehsan67** [comment]
@arheimberger  Please look at the report that I generated on 6-4-2015 in your email

**Comment by ehsan67** [comment]
@arheimberger  Please confirm if fixed

**Comment by arheimberger** [comment]
Fixed, please push to staging

**Comment by ehsan67** [comment]
pushed

**Comment by arheimberger** [comment]
Completed.
