### ISSUE TITLE
Accident Report - Causing Sync Error / Crash

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#65]
When an accident report is logged in the client side and the user changes the accident report number, if the report number entered is greater than 16 characters, the sync will crash and cause an error.  The field accepts 32 characters in both the client side field and database, but only accepts 16 in the entity framework.  Change needs to be made to accept 32 everywhere.  

This requires a server change and should be completed in the next release that will include server changes.

**Comment by ehsan67** [comment]
Fixed, to be tested in next update
