### ISSUE TITLE
Field App - Inspector Tracking - Date

### ISSUE THREAD

**Issue by arheimberger** [BC89/mfs_client_issues#9]
Inspectors have expressed a need to be able to change the date to a previous date for an inspections.  Currently you can only enter a date on or after the date inspection was created, but there are times when they need to enter the inspection for a date prior.

Steps to recreate:
1) Create a new inspection
2) Enter Inspector Tracking section
3) Select a date prior to the current day
4) Observe error

**Comment by ehsan67** [comment]
Fixed , needs to be tested

**Comment by arheimberger** [comment]
Completed in release 1.1.2.11.  Users now able to enter a date previous to inspection date, reports should use the inspector tracking date, unless one is not available, then use inspection date.
